board: toradex: mx4: Add missing include
board/toradex/mx4_v61/../mx4_common/mx4_common.c: In function
'ping_mx4_pic':
board/toradex/mx4_v61/../mx4_common/mx4_common.c:37:11: error: 'EINVAL'
undeclared (first use in this function)
board/toradex/mx4_v61/../mx4_common/mx4_common.c:37:11: note: each
undeclared identifier is reported only once for each function it appears
in
scripts/Makefile.build:276: recipe for target
'board/toradex/mx4_v61/../mx4_common/mx4_common.o' failed